# Generated by Django 3.2.4 on 2021-12-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='channel_post', to='mainapp.Comments'),
        ),
    ]
