# Generated by Django 3.2.4 on 2021-12-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_video_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='is_creator',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
